version: "2"

services:

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: unless-stopped
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "default"
      - "proxy-tier"

  proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - "proxy"
    depends_on:
      - "proxy"
    networks:
      - "default"
      - "proxy-tier"

  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=feed.belanyi.fr
      - LETSENCRYPT_HOST=feed.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - PGID=1001
      - PUID=1000
    volumes:
      - ./freshrss:/config
    ports:
      - "667:80"
    networks:
      - "proxy-tier"
      - "default"

  calibre:
    image: linuxserver/calibre
    container_name: calibre
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=calibre.belanyi.fr
      - LETSENCRYPT_HOST=calibre.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - VIRTUAL_PORT=8080
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - GUAC_USER=ambroisie # optional
      - GUAC_PASS=3e0109e17016d3a2dc0a350d9a9ca104 # password
    volumes:
      - ./library:/config
      - ./books_to_add:/books_to_add
    ports:
      - "8080:8080"
      #- "8081:8081"
    networks:
      - "default"
      - "proxy-tier"

  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=library.belanyi.fr
      - LETSENCRYPT_HOST=library.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ./calibre-web:/config
      - ./library:/books
    ports:
      - "8083:8083"
    networks:
      - "default"
      - "proxy-tier"

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=gitea.belanyi.fr
      - LETSENCRYPT_HOST=gitea.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - VIRTUAL_PORT=3000
      - ROOT_URL=https://gitea.belanyi.fr
      - DOMAIN=gitea.belanyi.fr
      - PROTOCOL=http
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
    ports:
      - "5000:3000"
      - "222:22"
    networks:
      - "proxy-tier"
      - "default"

volumes:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
