version: "2"

services:

  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    restart: unless-stopped
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "default"
      - "proxy-tier"

  proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - "proxy"
    depends_on:
      - "proxy"
    networks:
      - "default"
      - "proxy-tier"

  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=feed.belanyi.fr
      - LETSENCRYPT_HOST=feed.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - PGID=1001
      - PUID=1000
    volumes:
      - ./freshrss:/config
    ports:
      - "667:80"
    networks:
      - "proxy-tier"
      - "default"

  calibre:
    image: linuxserver/calibre
    container_name: calibre
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=calibre.belanyi.fr
      - LETSENCRYPT_HOST=calibre.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - VIRTUAL_PORT=8080
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - GUAC_USER=ambroisie # optional
      - GUAC_PASS=3e0109e17016d3a2dc0a350d9a9ca104 # password
    volumes:
      - ./library:/config
      - ./books_to_add:/books_to_add
    ports:
      - "8080:8080"
      #- "8081:8081"
    networks:
      - "default"
      - "proxy-tier"

  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=library.belanyi.fr
      - LETSENCRYPT_HOST=library.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ./calibre-web:/config
      - ./library:/books
    ports:
      - "8083:8083"
    networks:
      - "default"
      - "proxy-tier"

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=gitea.belanyi.fr
      - LETSENCRYPT_HOST=gitea.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - VIRTUAL_PORT=3000
      - ROOT_URL=https://gitea.belanyi.fr
      - DOMAIN=gitea.belanyi.fr
      - PROTOCOL=http
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
    ports:
      - "5000:3000"
      - "222:22"
    networks:
      - "proxy-tier"
      - "default"

  tenma:
    image: hmhrex/tenma
    container_name: tenma
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=tenma.belanyi.fr
      - LETSENCRYPT_HOST=tenma.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
    volumes:
      - ./comics:/tenma/files
      - ./tenma:/tenma/media
    ports:
      - "8085:8000"
    networks:
      - "proxy-tier"
      - "default"

  pyload:
    image: linuxserver/pyload
    container_name: pyload
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=pyload.belanyi.fr
      - LETSENCRYPT_HOST=pyload.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - VIRTUAL_PORT=8000
      - TZ=Europe/Paris
      - PUID=1000
      - PGID=1000
    volumes:
      - ./pyload:/config
      - ~/downloads:/downloads
    ports:
      - 8000:8000
      - 7227:7227 #optional
    networks:
      - "default"
      - "proxy-tier"

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=transmission.belanyi.fr
      - LETSENCRYPT_HOST=transmission.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - VIRTUAL_PORT=9091
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      # UI can be combustion-release, transmission-web-control, or kettu
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=Ambroisie #optional
      - PASS=yb87AdRXZJPK2w^QFY!BM8QD4Pn5rpeK #optional
    volumes:
      - ./transmission:/config
      - ~/downloads:/downloads
      - ~/downloads/blackhole:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - "default"
      - "proxy-tier"

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=jackett.belanyi.fr
      - LETSENCRYPT_HOST=jackett.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./jackett:/config
      - ~/downloads/blackhole:/downloads
    ports:
      - 9117:9117
    networks:
      - "default"
      - "proxy-tier"

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=sonarr.belanyi.fr
      - LETSENCRYPT_HOST=sonarr.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022 #optional
    volumes:
      - ./sonarr:/config
      - ~/videos/shows:/tv
      - ~/downloads:/downloads
    ports:
      - 8989:8989
    networks:
      - "default"
      - "proxy-tier"

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=radarr.belanyi.fr
      - LETSENCRYPT_HOST=radarr.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022 #optional
    volumes:
      - ./radarr:/config
      - ~/videos/movies:/movies
      - ~/downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - "default"
      - "proxy-tier"

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=bazarr.belanyi.fr
      - LETSENCRYPT_HOST=bazarr.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022 #optional
    volumes:
      - ./bazarr:/config
      - ~/videos/movies:/movies
      - ~/videos/shows:/tv
    ports:
      - 6767:6767
    networks:
      - "default"
      - "proxy-tier"

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=lidarr.belanyi.fr
      - LETSENCRYPT_HOST=lidarr.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - UMASK_SET=022 #optional
    volumes:
      - ./lidarr:/config
      - ~/music:/music
      - ~/downloads:/downloads
    ports:
      - 8686:8686
    networks:
      - "default"
      - "proxy-tier"

  quassel-core:
    image: linuxserver/quassel-core
    container_name: quassel-core
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=quassel.belanyi.fr
      - LETSENCRYPT_HOST=quassel.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - VIRTUAL_PORT=4242
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - RUN_OPTS=--config-from-environment #optional
      - DB_BACKEND=SQLite
      - AUTH_AUTHENTICATOR=Database
    volumes:
      - ./quassel:/config
    ports:
      - 4242:4242
      - 113:10113 #optional

  grocy:
    image: linuxserver/grocy
    container_name: grocy
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=grocy.belanyi.fr
      - LETSENCRYPT_HOST=grocy.belanyi.fr
      - LETSENCRYPT_EMAIL=brunobelanyi@gmail.com
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./grocy:/config
    ports:
      - 9283:80

volumes:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
